name: Generate ASCII Artwork
run-name: Run by @${{ github.actor }}

on:
  workflow_dispatch: 

jobs: 
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Rawr" >> dragon.txt

      - name: Upload text file
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Test File Exists
        run: grep -i "rawr" dragon.txt

  deploy_job_3:
    needs: [test_job_2]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying ... .. .