name: Matrix Configuration

# https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

on:
  workflow_dispatch: 

jobs:
  # deploy-on-ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Echo Docker details
  #       run: docker info
      
  #     - name: Run Images
  #       run: docker run hello-world

  # deploy-on-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Echo Docker Details
  #       run: docker info

  #     - name: Run Images
  #       run: docker run hello-world
  hello_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04 windows-latest]
        images: [hello-world, alpine, williamyeh/wrk]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Images
        run: docker run ${{ matrix.images }}